### ISSUE TITLE
Almost all of the links at the end of the main page Learn More list are bad

### ISSUE THREAD

**Issue by awwad** [SeattleTestbed/docs#27]
https://github.com/SeattleTestbed/docs#how-do-i-learn-more

**Comment by lukpueh** [comment]
Thanks for pointing this out! This is actually a good thing, because it suggests that the old `*.wiki` files have been converted to the wanted `*.md` format.

I once mentioned that along the conversion process one should check for such links:
https://github.com/SeattleTestbed/docs/issues/4#issuecomment-219811824.

**Comment by aaaaalbert** [comment]
We also have a few fixes pending, see #26.
